#!/bin/bash

VERSION=0.4.0-M4
SCALA_VERSION=2.11.7

DIR="$(cd "$(dirname "$0")"; pwd)"

if [ ! -d "$DIR/target/scala-2.11/classes" ]; then
  sbt compile
fi

export COURSIER_CACHE="$DIR/.cache"

CREATE='val replesent = new REPLesent(slides)'
IMPORT='import replesent._'
PREDEF='
classpath.add("org.scala-lang" % "scala-compiler" % "2.11.7")
classpath.addPath("""'"$DIR"'/target/scala-2.11/classes""")

val slides = """'"$DIR"'/slides.txt"""

'"$CREATE"'
'"$IMPORT"'

def reload(implicit eval: ammonite.api.Eval): Unit = {
  eval("""'"$CREATE"'""")
  eval("""'"$IMPORT"'""")
}

def r(implicit eval: ammonite.api.Eval): Unit = reload

def q = exit

f
'

exec "$(dirname "$0")/coursier" launch \
  com.github.alexarchambault.ammonium:shell_$SCALA_VERSION:$VERSION \
  -I ammonium-compile:com.github.alexarchambault.ammonium:shell-api_$SCALA_VERSION:$VERSION \
  -I ammonium-macro:org.scala-lang:scala-compiler:$SCALA_VERSION \
  -i ammonium-compile,ammonium-macro \
  --checksum none \
  -r sonatype:releases \
  -- -- --predef="$PREDEF" "$@"
