#!/bin/bash

VERSION=0.4.0-M3-replesent
SCALA_VERSION=2.11.7

export COURSIER_CACHE="$(cd "$(dirname "$0")"; pwd)/.cache"

CREATE='val replesent = new REPLesent(sys.props("user.home") + "/projects/REPLesent/REPLesent.txt")'
IMPORT='import replesent._'
PREDEF='
classpath.add("org.scala-lang" % "scala-compiler" % "2.11.7")
classpath.addPath(sys.props("user.home") + "/projects/REPLesent/target/scala-2.11/classes")

'"$CREATE"'
'"$IMPORT"'

def reload(implicit eval: ammonite.api.Eval): Unit = {
  eval("""'"$CREATE"'""")
  eval("""'"$IMPORT"'""")
}

def r(implicit eval: ammonite.api.Eval): Unit = reload
'

exec "$(dirname "$0")/coursier" launch \
  com.github.alexarchambault.ammonium:shell_$SCALA_VERSION:$VERSION \
  -I ammonium-compile:com.github.alexarchambault.ammonium:shell-api_$SCALA_VERSION:$VERSION \
  -I ammonium-macro:org.scala-lang:scala-compiler:$SCALA_VERSION \
  -i ammonium-compile,ammonium-macro \
  --checksum none \
  -- -- --predef="$PREDEF" "$@"
